name: 'TITLE1' # change here for `name`
concurrency: report-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
  schedule:
    - cron: '0 2 21 * *' # change here for `cron`; Schedule on CST 10 during 20th day of every month.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@main
        - name: 'Set up Python'
          uses: actions/setup-python@main
          with:
            python-version: '3.x'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Time wait ${{ github.event.inputs.delays }}
          if: ${{ github.event.inputs.delays != '' }}
          run: sleep ${{ github.event.inputs.delays }}
        - name: 'Send Timed Message to Wechat'
          env:
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TITLE: ${{ secrets[format('TITLE{0}', github.workflow)] }}
            MSG: ${{ secrets[format('MSG{0}', github.workflow)] }}
            CONTENT: ${{ secrets[format('CONTENT{0}', github.workflow)] }}
            IMAGE: ${{ secrets[format('IMAGE{0}', github.workflow)] }}
            CORPID: ${{ secrets.CORPID }}
            CORPSECRET: ${{ secrets.CORPSECRET }}
            AGENTID: ${{ secrets.AGENTID }}
          run: python Wechat-Timed-Message.py
        - name: 'Re-run workflow if failed and GPATOKEN set'
          if: ${{ failure() }}
          run: |
            workflow_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | grep workflow_url | cut -d \" -f 4` \
            && curl \
            -X POST \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $workflow_url/dispatches \
            -d '{"ref":"${{ github.ref }}", "inputs": { "delays": "30m" }}'
